var ALWAYS = ["OPTED_OUT", "HUMAN_REVIEW", "ERROR"];
var TRANSITIONS = {
  NEW: ["RESEARCHING", "DISQUALIFIED", "DUPLICATE", ...ALWAYS],
  RESEARCHING: ["RESEARCHED", "DISQUALIFIED", ...ALWAYS],
  RESEARCHED: ["QUALIFYING", "DISQUALIFIED", ...ALWAYS],
  QUALIFYING: ["QUALIFIED", "DISQUALIFIED", ...ALWAYS],
  QUALIFIED: ["OUTREACH_READY", "DISQUALIFIED", ...ALWAYS],
  OUTREACH_READY: ["OUTREACH_SENT", "DISQUALIFIED", ...ALWAYS],
  OUTREACH_SENT: ["AWAITING_REPLY", "BAD_NUMBER", ...ALWAYS],
  AWAITING_REPLY: ["REPLIED", "NOT_INTERESTED", "BAD_NUMBER", "LOST", ...ALWAYS],
  REPLIED: ["INTERESTED", "NOT_INTERESTED", "LOST", ...ALWAYS],
  INTERESTED: ["DEMO_APPROVED", "NOT_INTERESTED", "LOST", ...ALWAYS],
  DEMO_APPROVED: ["DEMO_BUILDING", "NOT_INTERESTED", "LOST", ...ALWAYS],
  DEMO_BUILDING: ["DEMO_QA", "DEMO_APPROVED", "LOST", ...ALWAYS],
  DEMO_QA: ["DEMO_READY", "DEMO_BUILDING", "LOST", ...ALWAYS],
  DEMO_READY: ["DEMO_SENT", "DEMO_BUILDING", "LOST", ...ALWAYS],
  DEMO_SENT: ["DEMO_VIEWED", "PRICING_VIEWED", "NOT_INTERESTED", "LOST", ...ALWAYS],
  DEMO_VIEWED: ["PRICING_VIEWED", "NOT_INTERESTED", "LOST", ...ALWAYS],
  PRICING_VIEWED: ["CHECKOUT_STARTED", "NOT_INTERESTED", "LOST", ...ALWAYS],
  CHECKOUT_STARTED: ["WON", "LOST", ...ALWAYS],
  WON: ["ONBOARDING", "LOST", ...ALWAYS],
  ONBOARDING: ["BUILD_FINAL", "LOST", ...ALWAYS],
  BUILD_FINAL: ["LIVE", "LOST", ...ALWAYS],
  LIVE: ["ACTIVE_CUSTOMER", "LOST", ...ALWAYS],
  ACTIVE_CUSTOMER: ["LOST", ...ALWAYS],
  DISQUALIFIED: ["HUMAN_REVIEW"],
  OPTED_OUT: [],
  NOT_INTERESTED: ["HUMAN_REVIEW", "OPTED_OUT"],
  BAD_NUMBER: ["HUMAN_REVIEW", "OPTED_OUT"],
  DUPLICATE: ["HUMAN_REVIEW"],
  // HUMAN_REVIEW was a trapdoor: it only exited to RESEARCHING/QUALIFYING, so a
  // lead escalated from DEMO_BUILDING (or anywhere else) could never rejoin
  // the pipeline where it left off.
  HUMAN_REVIEW: [
    "RESEARCHING",
    "RESEARCHED",
    "QUALIFYING",
    "QUALIFIED",
    "OUTREACH_READY",
    "OUTREACH_SENT",
    "AWAITING_REPLY",
    "REPLIED",
    "INTERESTED",
    "DEMO_APPROVED",
    "DEMO_BUILDING",
    "DEMO_QA",
    "DEMO_READY",
    "DEMO_SENT",
    "DEMO_VIEWED",
    "PRICING_VIEWED",
    "CHECKOUT_STARTED",
    "WON",
    "ONBOARDING",
    "BUILD_FINAL",
    "LIVE",
    "ACTIVE_CUSTOMER",
    "DISQUALIFIED",
    "NOT_INTERESTED",
    "OPTED_OUT",
    "LOST",
    "ERROR"
  ],
  // ERROR used to only reach HUMAN_REVIEW, so any error permanently destroyed
  // the lead's pipeline position.
  ERROR: ["HUMAN_REVIEW", "OPTED_OUT"],
  LOST: ["HUMAN_REVIEW", "OPTED_OUT"]
};
function canTransition(from, to) {
  return TRANSITIONS[from].includes(to);
}
__name(canTransition, "canTransition");
function allowedTransitions(from) {
  return TRANSITIONS[from];
}
__name(allowedTransitions, "allowedTransitions");

